M48
; DRILL file {KiCad 9.0.6} date 2026-04-17T18:14:31+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-17T18:14:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X113.399Y-130.952
X118.249Y-130.952
T2
X113.099Y-133.982
X118.549Y-133.982
M30
