M48
; DRILL file {KiCad 9.0.6} date 2026-06-26T11:48:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-26T11:48:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X113.399Y-131.082
X118.249Y-131.082
T2
X113.099Y-134.112
X118.549Y-134.112
M30
